{
 "title": "Loki Logs Dashboard",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "All MedApp Services Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=~\"medapp-.*\"}"
    }
   ]
  },
  {
   "title": "Error Count by Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(container_name) (count_over_time({container_name=~\"medapp-.*\"} |~ \"(error|ERROR|Error)\" [$__interval]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{container_name=~\"medapp-.*\"} |= `error` or |= `ERROR` or |= `Error`"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{container_name=~\"medapp-.*\"} |= `warn` or |= `WARN` or |= `Warning`"
    }
   ]
  },
  {
   "title": "Service Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{container_name=\"$service\"}"
    }
   ]
  }
 ]
}